import { useState, useEffect } from 'react';
import { chatApi } from '@/lib/api';

export interface Message {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  timestamp: Date;
}

export function useAIChat() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      sender: 'ai',
      text: "Hi! I'm your AI claims assistant. I can help you with claim status updates, policy questions, or guide you through the submission process. How can I assist you today?",
      timestamp: new Date(),
    },
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const [sessionId, setSessionId] = useState<string | undefined>(undefined);

  // Generate a session ID on mount
  useEffect(() => {
    // Session ID will be generated by backend on first message
  }, []);

  const sendMessage = async (text: string) => {
    // Add user message
    const userMessage: Message = {
      id: Date.now().toString(),
      sender: 'user',
      text,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, userMessage]);

    // Show typing indicator
    setIsTyping(true);

    try {
      // Call real API
      const response = await chatApi.sendMessage(text, sessionId);

      // Update session ID if this is the first message
      if (!sessionId && response.session_id) {
        setSessionId(response.session_id);
      }

      // Add AI response
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        sender: 'ai',
        text: response.response,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, aiResponse]);
    } catch (error) {
      console.error('Error sending message:', error);

      // Add error message
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        sender: 'ai',
        text: "I'm having trouble connecting right now. Please try again in a moment or contact support at support@claimwise.com.",
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsTyping(false);
    }
  };

  const clearSession = async () => {
    if (sessionId) {
      try {
        await chatApi.clearSession(sessionId);
        setSessionId(undefined);
        setMessages([
          {
            id: '1',
            sender: 'ai',
            text: "Hi! I'm your AI claims assistant. I can help you with claim status updates, policy questions, or guide you through the submission process. How can I assist you today?",
            timestamp: new Date(),
          },
        ]);
      } catch (error) {
        console.error('Error clearing session:', error);
      }
    }
  };

  return { messages, sendMessage, isTyping, clearSession, sessionId };
}

